- name: mongdodb.repo file 
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Mongodb Installation
  ansible.builtin.dnf:
    name: mongodb-org
    state: present
    
- name: Service restart
  ansible.builtin.service:
    name: mongod
    state: restart
    enabled: yes

- name: enable remote connections
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'