- name: disable nginx
  ansible.builtin.command: dnf module disable nginx -y

- name: disable nginx
  ansible.builtin.command: dnf module enable nginx:1.24 -y

- name: disable nginx
  ansible.builtin.dnf:
    name: nginx
    state: present
- name: start & enable nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: remove html directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: create html directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: download the app contents
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
    dest: /tmp/frontend.zip

- name: copy the nginx conf
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx.nginx.conf

- name: extract the frondend code
  ansible.builtin.unarchive:
    src: /tmp/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: service restart
  ansible.builtin.service:
    name: nginx
    state: restarted

