- name: nodejs installation
  include_role: 
    name: common
    tasks_from: nodejs.yaml

- name: Create system user
  include_role:
    name: common
    tasks_from: system_user.yaml
  
- name: download application code
  include_role:
    name: common
    tasks_from: app-code-download.yaml

- name: download dependencies npm
  community.general.npm:
    name: npm
    path: /app
    state: present

- name: setting "{{ component }}".service
  ansible.builtin.include.role:
    name: common
    tasks_from: app-code-download.yaml

- name: Daemon_reload & service restart
  include_role: 
    name: common
    tasks_from: daemon_reload

- name: Copy mongodb client repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install mongodb client
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: present

- name: check products loaded or not
  tags:
  - load_data
  ansible.builtin.command: mongosh --host mongodb.singireddy.shop --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
  register: catalogue_output

- name: Display the data present in mongodb
  ansible.builtin.debug:
    msg: "{{ catalogue_output }}"

- name: Load Product informaiton if there is no data
  ansible.builtin.shell: mongosh --host mongodb.singireddy.shop < /app/db/master-data.js
  when: catalogue_output.stdout | int < 0

    
      
