- name: System User creation
  ansible.builtin.user:
    name: roboshop
    shell: /sbin/nologin
    home: /app
    system: yes

- name: /app dir creation
  ansible.builtin.file:
    path: /app
    state: directory



  